insert into tb_tipos_eventos
           (Descricao)
    values ('Gol')
         , ('Cartão Amarelo')
         , ('Cartão Vermelho')
         , ('Gol Olímpico')           
         , ('Gol (P)')
         , ('Pênalti (X)')
         , ('Gol Anulado')
         , ('Gol Contra')
