insert into tb_campeonatos_fases
           (Descricao)
     values('Rodada Preliminar')
         , ('Fase de Grupos')
         , ('Primeira Rodada')
         , ('Primeira Fase')
         , ('Segunda Rodada')
         , ('Segunda Fase')
         , ('Terceira Rodada')
         , ('Terceira Fase')
         , ('Triangular Final')
         , ('Quadrangular Final')
         , ('Oitavas de Final')
         , ('Quartas de Final')
         , ('Semifinais')
         , ('Disputa de 3º e 4º lugar')
         , ('Final')
