insert into tb_paises (Nome_Pais)

values ('Abecásia')
      ,('Afeganistão')
      ,('África do Sul')
      ,('Albânia')
      ,('Alemanha')
      ,('Alemanha Ocidental')
      ,('Alemanha Oriental')
      ,('Andorra')
      ,('Angola')
      ,('Anguilla')
      ,('Antígua e Barbuda')
      ,('Arábia Saudita')
      ,('Argélia')
      ,('Argentina')
      ,('Armênia')
      ,('Aruba')
      ,('Austrália')
      ,('Áustria')
      ,('Azerbaijão')
      ,('Bahamas')
      ,('Bahrein')
      ,('Bangladesh')
      ,('Barbados')
      ,('Belarus')
      ,('Bélgica')
      ,('Belize')
      ,('Benin')
      ,('Bermudas')
      ,('Birmânia')
      ,('Bolívia')
      ,('Bósnia e Herzegovina')
      ,('Botsuana')
      ,('Brasil')
      ,('Brunei')
      ,('Bulgária')
      ,('Burkina Faso')
      ,('Burundi')
      ,('Butão')
      ,('Cabo Verde')
      ,('Camarões')
      ,('Camboja')
      ,('Canadá')
      ,('Catar')
      ,('Cazaquistão')
      ,('CEI')
      ,('Chade')
      ,('Chile')
      ,('China')
      ,('Chipre')
      ,('Chipre do Norte')
      ,('Cingapura')
      ,('Colômbia')
      ,('Comores')
      ,('Congo')
      ,('Coréia do Norte')
      ,('Coréia do Sul')
      ,('Costa do Marfim')
      ,('Costa Rica')
      ,('Croácia')
      ,('Cuba')
      ,('Curaçao')
      ,('Dinamarca')
      ,('Djibuti')
      ,('Dominica')
      ,('Egito')
      ,('El Salvador')
      ,('Emirados Árabes Unidos')
      ,('Equador')
      ,('Eritreia')
      ,('Escócia')
      ,('Eslováquia')
      ,('Eslovênia')
      ,('Espanha')
      ,('Estados Unidos')
      ,('Estônia')
      ,('Etiópia')
      ,('Fiji')
      ,('Filipinas')
      ,('Finlândia')
      ,('França')
      ,('Gabão')
      ,('Gâmbia')
      ,('Gana')
      ,('Géorgia')
      ,('Gibraltar')
      ,('Granada')
      ,('Grécia')
      ,('Groenlândia')
      ,('Guadalupe')
      ,('Guam')
      ,('Guatemala')
      ,('Guiana')
      ,('Guiana Francesa')
      ,('Guiné')
      ,('Guiné-Bissau')
      ,('Guiné Equatorial')
      ,('Haiti')
      ,('Holanda')
      ,('Honduras')
      ,('Hong Kong')
      ,('Hungria')
      ,('Iêmen')
      ,('Ilhas Cayman')
      ,('Ilhas Cook')
      ,('Ilhas Faroé')
      ,('Ilhas Marianas Setentrionais')
      ,('Ilhas Marshall')
      ,('Ilhas Maurício')
      ,('Ilhas Salomão')
      ,('Ilhas Turks e Caicos')
      ,('Ilhas Virgens')
      ,('Ilhas Virgens Britânicas')
      ,('Império Áustro-Húngaro')
      ,('Índia')
      ,('Indonésia')
      ,('Inglaterra')
      ,('Irã')
      ,('Iraque')
      ,('Irlanda')
      ,('Irlanda do Norte')
      ,('Islândia')
      ,('Israel')
      ,('Itália')
      ,('Iugoslávia')
      ,('Jamaica')
      ,('Japão')
      ,('Jordânia')
      ,('Kiribati')
      ,('Kosovo')
      ,('Kuwait')
      ,('Laos')
      ,('Lesoto')
      ,('Letônia')
      ,('Líbano')
      ,('Libéria')
      ,('Líbia')
      ,('Liechtenstein')
      ,('Lituânia')
      ,('Luxemburgo')
      ,('Macedônia')
      ,('Macedônia do Norte')
      ,('Madagascar')
      ,('Malásia')
      ,('Malawi')
      ,('Maldivas')
      ,('Mali')
      ,('Malta')
      ,('Marrocos')
      ,('Martinica')
      ,('Mauritânia')
      ,('México')
      ,('Micronésia')
      ,('Moçambique')
      ,('Moldávia')
      ,('Mônaco')
      ,('Mongólia')
      ,('Montenegro')
      ,('Montserrat')
      ,('Myanmar')
      ,('Namíbia')
      ,('Nauru')
      ,('Nepal')
      ,('Nicarágua')
      ,('Níger')
      ,('Nigéria')
      ,('Noruega')
      ,('Nova Caledônia')
      ,('Nova Zelândia')
      ,('Omã')
      ,('Ossétia do Sul')
      ,('País de Gales')
      ,('Palau')
      ,('Palestina')
      ,('Panamá')
      ,('Papua-Nova Guiné')
      ,('Paquistão')
      ,('Paraguai')
      ,('Perú')
      ,('Polinésia')
      ,('Polônia')
      ,('Porto Rico')
      ,('Portugal')
      ,('Quênia')
      ,('Quirguistão')
      ,('Reino Unido')
      ,('República Árabe Saaraui Democrática')
      ,('República Centro-Africana')
      ,('República Democrática do Congo')
      ,('República Dominicana')
      ,('República Tcheca')
      ,('Romênia')
      ,('Ruanda')
      ,('Rússia')
      ,('Samoa')
      ,('Samoa Americana')
      ,('Saint-Martin')
      ,('San Marino')
      ,('Santa Lúcia')
      ,('São Cristóvão e Névis')
      ,('São Tomé e Príncipe')
      ,('São Vicente e Granadinas')
      ,('Senegal')
      ,('Serra Leoa')
      ,('Sérvia')
      ,('Sérvia e Montenegro')
      ,('Seychelles')
      ,('Síria')
      ,('Somália')
      ,('Sri Lanka')
      ,('Suazilândia')
      ,('Sudão')
      ,('Sudão do Sul')
      ,('Suécia')
      ,('Suíça')
      ,('Suriname')
      ,('Tadjiquistão')
      ,('Tailândia')
      ,('Taipei')
      ,('Taiti')
      ,('Taiwan')
      ,('Tanzânia')
      ,('Tchecoslováquia')
      ,('Timor-Leste')
      ,('Togo')
      ,('Tonga')
      ,('Trinidad & Tobago')
      ,('Tunísia')
      ,('Turcomenistão')
      ,('Turquia')
      ,('Tuvalu')
      ,('Ucrânia')
      ,('Uganda')
      ,('União Soviética')
      ,('Uruguai')
      ,('Uzbequistão')
      ,('Vanuatu')
      ,('Vaticano')
      ,('Venezuela')
      ,('Vietnã')
      ,('Wallis e Futuna')
      ,('Zaire')
      ,('Zâmbia')
      ,('Zimbábue')
