CREATE TABLE tb_estados
(ID_Estado NUMERIC(15, 0) IDENTITY(1,1) PRIMARY KEY NOT NULL
,Nome_Estado VARCHAR(128) NOT NULL
,ID_Pais INT NOT NULL
,Sigla_Estado VARCHAR(3) NULL)

ALTER TABLE tb_estados WITH CHECK ADD FOREIGN KEY(ID_Pais)
REFERENCES tb_paises (ID_Pais)
GO
