create table tb_jogadores_habil_espec_descricoes
(Desc_Dribbling varchar(320)
,Desc_Tactical_Dribble varchar(320)
,Desc_Positioning varchar(320)
,Desc_Playmaking varchar(320)
,Desc_Scoring varchar(320)
,Desc_Post_Player varchar(320)
,Desc_Lines varchar(320)
,Desc_Middle_Shooting varchar(320)
,Desc_Side varchar(320)
,Desc_Center varchar(320)
,Desc_Curling_Shot varchar(320))
